services:
  - type: worker
    name: telegram-downloader-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: ADMIN_ID
        value: your_admin_id_here
      - key: REQUIRED_CHANNELS
        value: "@channel1,@channel2"  # Optional - remove if not needed
      - key: PYTHON_VERSION
        value: 3.11.4
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
